export default interface infoTatuConteudos {
    id:number,
    id_atracao:number,
    nome:string,
    autor: string,
    tipo: number,
    audio_desc : string,
    descricao: string,
    video_libras: string,
    created_at: string, 
    updated_at: string,
    ano: string,
    status: string,
    desc_curta: string,
    active:number,
    analise: number,
    audio_guia: string,
    lat:string,
    long:string,
    espaco:string,
    visible_everywhere:number,
    latitude: string ,
    longitude: string ,
    audio_desc_ios: string,
    audio_guia_ios: string,
    imagem_conteudo:
    [{
        id: number,
        local: string,
        nome: string,
        id_conteudo:number,
        created_at: string,
        updated_at: string,
        thumb: string,
        reduzida: string,
    }],
    beacon:{
        id: number,
        id_conteudo: number,
        cod_major: string,
        dat_instalacao: string,
        ter_prev_bateria: string,
        created_at: string,
        updated_at: string,
        id_atracao: string,
        type: string,
    }
}