export default interface infoTatuAtracoes {
  a_visual: number,
  id: number,
  a_fisica: number,
  a_auditiva: number,
  nome: string,
  endereco: string,
  horario_inicio: string,
  horario_termino: string,
  responsavel: string,
  descricao: string,
  contato: string,
  tipo: number,
  created_at: string,
  updated_at: string,
  imagem: string,
  active: number,
  latitude: string,
  longitude: string,
  temp: string,
  weather: string,
  thumb: string,
  beacon_identifier: string,
  beacon_id: number,
  type: string,
}